### ISSUE TITLE
WebApp folder and Classes folder forget it's setting

### ISSUE THREAD

**Issue by Trakhan** [guikeller/jetty-runner#12]
I have configured two jetty run configurations (one for each of my computers). They differ in WebApp Folder a Classes Folder configuration, since my project is checked out into differnt location.

I can set theese configurations and jetty works just fine until idea restart. After starting Idea anew, the second created configuration conatins values from the first one.

My guess is that it uses first found configuration for both of them.

**Comment by guikeller** [comment]
Hi Trakhan,

Thanks for the bug report, I will work on it as soon as I get my new laptop set up.
My old one died on me, but I should be able to replicate the bug easily and fix it.

I suspect that is something to do with the model and writing/reading to/from the disk.
Here is the class that might be the culprit: JettyRunnerConfiguration

Thank you very much.

Kind regards,
Gui

**Comment by guikeller** [comment]
Hi Trakhan,

I have fixed this issue during the weekend and should soon be releasing a new version of the plugin.
It should also include the new feature requested on GitHub Issue #13 

The new version should come out on the weekend or early next week as I have been pretty busy with other things.

Cheers,
Gui

**Comment by guikeller** [comment]
Hi Trakhan,

A new release of the plugin is out, please download it.
It includes the bug fix for this issue.

Thanks for your collaboration.

Kind regards,
Gui

**Comment by guikeller** [comment]
Hi Trakhan,

Could you please head over to the JetBrains plugin page and provide some feedback / rate the plugin and/or if possible do give jetty-runner a star on GitHub; show your support and appreciation for the project :)
https://plugins.jetbrains.com/plugin/7505

Thank you very much for your help. 

Kind regards,
Gui
