### ISSUE TITLE
Environment Variable passing/setting

### ISSUE THREAD

**Issue by Ramblurr** [guikeller/jetty-runner#13]
It would be invaluable to be able to pass env vars to jetty, either by setting them in the run config or by inheriting them from IDEA's process' env.

See the maven runner for an example:

![tiles-05](https://cloud.githubusercontent.com/assets/14830/7746197/ca5f5e2c-ffb0-11e4-8cfa-6de07ddab6d9.png)
![tiles-05](https://cloud.githubusercontent.com/assets/14830/7746204/d4058b5e-ffb0-11e4-93a0-0596813aa2a8.png)

**Comment by Ramblurr** [comment]
I should note that Idea's environment is passed to the jetty runner, so if you start Idea with ENV vars set, the jetty process will inherit them. What I'd like to see is the ability to edit the env in the plugin's GUI.

**Comment by guikeller** [comment]
Hi Ramblurr,

I will investigate that on the weekend, I need to have a look on the JetBrains Plugin API documentation ( which is not the greatest ) and figure out how to implement it.

As you have mentioned you can start Idea with the env vars set or you could override them using a jetty-web.xml as an alternative.

It shouldn't be too difficult to do that though (famous last words).
Thanks for the feature / enhancement request.

Kind regards,
Gui

**Comment by guikeller** [comment]
Hi Ramblurr,

I have added the Env Vars setting to the plugin during the weekend, however it's experimental and should be used with extreme caution.

I need to merge the changes of my local dev branches and commit into master together with the fixes for GitHub Issue #12 

Cheers, Gui

**Comment by guikeller** [comment]
Hi Ramblurr,

A new release of the plugin is out, please download it.
It includes the feature that you have requested here in this issue.

Please note that is still **experimental** as I couldn't find clarity on the IntelliJ Plugin Development documentation about setting environment variables while spawning a new Java Process.

Thanks for your collaboration.

Kind regards,
Gui

**Comment by guikeller** [comment]
Hi Ramblurr,

Could you please head over to the JetBrains plugin page and provide some feedback / rate the plugin and/or if possible do give jetty-runner a star on GitHub; show your support and appreciation for the project :)
https://plugins.jetbrains.com/plugin/7505

Thank you very much for your help.

Kind regards,
Gui
