### ISSUE TITLE
Compatible with WebStorm?

### ISSUE THREAD

**Issue by gunnx** [guikeller/jetty-runner#23]
Hi, 
It was tagged with webstorm but is it meant to work with this application?
I installed the plugin but it gave an error when trying to setup.
Thanks

**Comment by guikeller** [comment]
Hi @gunnx ,

The plugin has automatically received the "webstorm tag" due it's little set of dependencies.

From what I understand webstorm is used to do some html / js / css dev.
Therefore, you could use a the plugin to serve some content - see the link below.
[Serving static content with Jetty](https://codepitbull.wordpress.com/2013/05/14/serving-static-content-with-jetty-9/
)

Could you please provide a bit more information about the error?
Please see [these instructions](https://github.com/guikeller/jetty-runner/blob/master/CONTRIBUTING.md) on how to help me identify the issue.
 
Cheers,
Gui

**Comment by gunnx** [comment]
Hi
Yes its for HTML/CSS/JS development and I was hoping I could integrate Jetty so I could copy content into the webapp and test all from within WebStorm. It can work outside no problem but when I saw the plugin thought I would try it.

Versions:
WebStorm v 11.0.3
Jetty Plugin v 1.1.3
JVM 1.7.0_67

When trying to setup the Jetty server it errors and this appears in the Event Log:
![screen shot 2016-02-01 at 10 55 45](https://cloud.githubusercontent.com/assets/1970063/12715458/5c260eec-c8d2-11e5-8417-845eee0299c0.png)

Thank you

**Comment by guikeller** [comment]
Hi @gunnx,

I have opened up a bug with the guys from IntelliJ
https://youtrack.jetbrains.com/issue/IJSDK-122
Let's see what they come back with.

Thank you very much for your help and collaboration.

Kind regards,
Gui

**Comment by guikeller** [comment]
Update on the issue - it has been moved into a project called _Plugins Repository_ (private).

![email_chain_plugin](https://cloud.githubusercontent.com/assets/8213310/12765641/774eaec0-ca64-11e5-8442-48a91da8e11b.PNG)

**Comment by guikeller** [comment]
More compatibility issues with WebStorm reported - please see:
http://stackoverflow.com/questions/35174281/how-to-resolve-class-not-found-error

**Comment by guikeller** [comment]
Hello all,

Sorry for the late reply - I had forgotten to update the issue here on GitHub.

I have heard back from Jetbrains and unfortunately their recommendation is to make the plugin compatible only with IntelliJ and IntelliJ CE.

I have made the changes locally already and will be releasing a new version of the plugin soon (time allowing).
This new version will be removing the WebStorm compatibility.

Thank you very much for your patience.

Cheers,
Gui
