### ISSUE TITLE
The importance of the classpath folder

### ISSUE THREAD

**Issue by dmg46664** [guikeller/jetty-runner#24]
Hello.
Please can you confirm that your Jetty Runner plugin expects all the jars and classes of your app to be built/made/copied to your classes output directory, and that the plugin cannot automatically set the classpath to point to the various jars in place? This is what I believe the Eclipse Jetty plugin and others do.

**Comment by guikeller** [comment]
Hi Daniel,

The JettyRunnerCommandLine class is the one responsible for setting up the classpath prior to launching Jetty. As you can see in the class it sets the classpath to "JDK_AND_CLASSES" using the JavaParameter class (IntelliJ).

Unfortunately I can't tell for sure its behaviour, you would need to ask the guys from IntelliJ to know the ins and outs of it. Hope it helps somehow.

Cheers,
Gui
