### ISSUE TITLE
How can i disable jetty log.

### ISSUE THREAD

**Issue by fwrq41251** [guikeller/jetty-runner#25]
console print a lot of log like "2016-04-01 11:45:46,423 DEBUG [user: unknown] org.eclipse.jetty.webapp....".
how can i disable this?

**Comment by guikeller** [comment]
Hi @fwrq41251 

Amend your log4j xml / properties file.
Tell it to log only FATAL for the following package: org.eclipse.jetty.webapp

Good luck, cheers!
