### ISSUE TITLE
jetty run failed

### ISSUE THREAD

**Issue by zhugw** [guikeller/jetty-runner#27]
hi 
    I just tried to use it, but when I run(ctrl+d) it , it throw below exception in console
```
Listening for transport dt_socket at address: 49480
Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.close()V
	at org.eclipse.jetty.runner.Runner.configure(Runner.java:228)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:556)

Process finished with exit code 1
```

Should I need install or config something else?

**Comment by guikeller** [comment]
Hi @zhugw 

The "NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.close()V" tells me that you have  multiple servlet-api versions being used by your project's dependencies and the plugin is using the wrong one to kick start Jetty.

Please see the following thread:
https://github.com/guikeller/jetty-runner/issues/20

Hope this helps, cheers.

**Comment by zhugw** [comment]
Thanks! the real cause is that I have below dependency
```
[INFO] |  +- org.apache.cxf:cxf-rt-transports-http-jetty:jar:3.0.0:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:8.1.15.v20140411:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-continuation:jar:8.1.15.v20140411:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-http:jar:8.1.15.v20140411:compile
[INFO] |  |  |     \- org.eclipse.jetty:jetty-io:jar:8.1.15.v20140411:compile
[INFO] |  |  |        \- org.eclipse.jetty:jetty-util:jar:8.1.15.v20140411:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-security:jar:8.1.15.v20140411:compile
[INFO] |  |  \- org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0:compile
```
Than I exclude this dependency, it could start successfully.
```
            <exclusions>
                <exclusion>
                    <groupId>org.apache.cxf</groupId>
                    <artifactId>cxf-rt-transports-http-jetty</artifactId>
                </exclusion>
            </exclusions>
```

BTW
Thank you for your plugin! but I feel it is not very convenient as in eclipse. In eclipse I only need right click then choose `Run As With Jetty`. But in intellij idea I have to explicitly config and must compile(cmd+F9) the project first.

**Comment by guikeller** [comment]
Hi @zhugw 

The "cxf-rt-transports-http-jetty" has a "org.eclipse.jetty.util.resource.Resource" class with a different signature for the "close" method; hence why you were getting the exception. All in all I am happy to hear that you got it working.

Thank you and I am glad that you've found it useful :+1: 

I see what you are saying about the inconveniences while setting up the plugin, and unfortunately these are issues that I did not manage to work around; but then those are one-off's. Thanks for your feedback though.

Cheers!
