### ISSUE TITLE
Exploded war deploy fails when http2 enabled

### ISSUE THREAD

**Issue by elmart** [guikeller/jetty-runner#28]
If I configure jetty to run http1, I can successfully run my webapp from IntelliJ. 
If I enable http2, server starts but webapp doesn't get deployed. 
I'm using the exploded war deploy. 
Any idea?

**Comment by guikeller** [comment]
Hi @elmart 

The HTTP2 is a feature that has been added on Jetty-9.3.
And the plugin uses Jetty-9.2 to kick start things under the hood which does not have that.

I will have a look on "Jetty-9.3.11.v20160721" and if is stable enough I will update the plugin.
In the meantime I will keep this issue / bug open as a feature request.

Cheers,
Gui

**Comment by elmart** [comment]
Were you able to try it?

**Comment by guikeller** [comment]
Sorry not yet, been busy with work and other commitments..
I will try during the weekend and will get a new release out if all goes well.

**Comment by guikeller** [comment]
Hi @elmart 

Good news all around! :smiley: 

I have managed to get some time and have upgraded to Jetty 9.3.x
It all works fine, only _downside_ is that the plugin **now depends on Java 8**.

Here is the release tag:
https://github.com/guikeller/jetty-runner/releases/tag/v1.2.0

The plugin has also been uploaded to IntelliJ / JetBrains so you should be able to update / get it.
Hope that you enjoy it and thanks for your patience.

Cheers,
Gui

**Comment by elmart** [comment]
Great!
Dependency on Java 8 is no problem for me. 
I'll try it as tomorrow at work. 
Thx very much for taking my suggestion into account.

**Comment by guikeller** [comment]
@elmart 

No problem! When you have got the chance could you please rate us on Plugins / JetBrains? :+1: 
If it is alright with you I would also appreciate a star here on GitHub. :smile: 

Thank you very much in advance. :bow: 
Good luck with your project.

Cheers,
Gui

**Comment by elmart** [comment]
I already starred you. ;-)
To rate, I will wait a bit, as it doesn't work for me yet.

Now that I could finally test it, I get the following exception:
https://gist.github.com/elmart/eaee72a98a8eb0bf58536bd01dd9b945

I'm on OSX 10.11.6, jdk1.8.0_60, jetty 9.3.12.
Attached my jetty's start.ini (renamed as start.ini.txt to be able to upload).
[start.ini.txt](https://github.com/guikeller/jetty-runner/files/505221/start.ini.txt)

Any idea?

**Comment by guikeller** [comment]
Hi @elmart 

It's classpath issue, the most common causes are to do with: ASM / CGLIB.

http://stackoverflow.com/questions/12166382/java-lang-incompatibleclasschangeerror-implementing-class-deploying-to-app-engi
https://github.com/ragnor/simple-spring-memcached/issues/22

Good luck with your project. :+1: 

Cheers,
Gui
