### ISSUE TITLE
Java 6 support issue

### ISSUE THREAD

**Issue by ivaris** [guikeller/jetty-runner#31]
Is this working for any java versions?. I am getting error for java6
 java.lang.UnsupportedClassVersionError: org/eclipse/jetty/runner/Runner : Unsupported major.minor version 52.0

**Comment by guikeller** [comment]
Hi @ivaris 

As mentioned on the plugin and github page:
"Minimum requirement: JVM / JDK / JRE v8".

If you are with Java v6 try and use the plugin **v1.0.0**.

List of Java versions and plugin compatibility matrix below:
Java 6: v.0.0.1 to v1.0.0 (jetty-runner-9.2.5)
Java 7: v.1.1.0 to v1.1.3 (jetty-runner-9.2.5)
Java 8: v1.2.0 (jetty-runner-9.3.11)

Hope this helps.

Cheers,
Gui
