### ISSUE TITLE
With multi web module, the classpath mixed

### ISSUE THREAD

**Issue by iacdingping** [guikeller/jetty-runner#33]
I have two springMvc web modules, , 
first , it couldn't determine classes folder.
second, i choose the classes folder manually(only one module's target/classes),  when I start jetty runner , All controller classes under two web modules has been scanned by spring .   May i have missing some configuration?   or isn't support for multi web modules ?   

My configure below:
jdk: 1.8
IntelliJ IDEA version : 
    IntelliJ IDEA 2016.3
    Build #IU-163.7743.44, built on November 18, 2016
   JRE: 1.8.0_91-b14 amd64
   JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Plugin Version: 1.2.0

![qq 20161124002732](https://cloud.githubusercontent.com/assets/5428965/20569943/c1d92280-b1dc-11e6-9018-7a8871318c82.png)

**Comment by guikeller** [comment]
Hi @iacdingping 

1st issue - That's known bug of the plugin, you have to "build / make" your project before creating a Jetty Runner configuration. I tried playing around with the IntelliJ API that does the project compilation with no luck as the documentation is very scarce and there are not many code samples out there.

2nd issue - From what I understood you have a multi-module web-project, and one/some of its module(s) is not getting picked up and added to the classpath. Is that right?

Delete your conf and try "building / making" the project with its dependencies before creating a Jetty Runner configuration. Make sure that all compiled classes are being put in the same target/classes directory. Also make sure that your multi-module project is properly configured:
https://zeroturnaround.com/rebellabs/jrebel-how-to-setting-up-multi-module-projects-in-intellij-idea/

The plugin code gathers for multi-modules projects (see line 49 to 54):
https://github.com/guikeller/jetty-runner/blob/master/src/main/java/com/github/guikeller/jettyrunner/model/JettyRunnerCommandLine.java

Alternatively have a look on how to use the "jetty.xml" so you can specify multiple folders to scan:
http://www.eclipse.org/jetty/documentation/9.4.x/jetty-xml-usage.html

Let me know how you go :)  :+1: 

Thanks,
Gui

**Comment by iacdingping** [comment]
Thanks for your replying,  maybe I have missing something,   I create another maven project modules , it could run successful ,  I will looking for the differences.   
Although, can you suggest me , how to using hot deploy with this plugin,  in eclipse , we don't need more plugin but only with the jetty-run-jetty plugin.  

Thanks very much

**Comment by iacdingping** [comment]
simplest example : 
root
|    a
|    web01
|    web02

this model could running success .

but if i change the module like: 
root
| a
| module01
    | module01-web01
    | module01-web02
| module02
    | module02-web01
    | module02-web02
things went wrong .  

I create a repositor here : https://github.com/iacdingping/jetty-runner-test

it could running under the jetty-server local config  just visit http://localhost:/jsm1w1/test
could you give me some suggestion to resolve this ?    I really don't like the jetty-server idea owner.

**Comment by guikeller** [comment]
Hi @iacdingping ,

I am sorry but I couldn't understand your explanation this time around.

Although, it seems to me that you got around the first issue by "making" the project.
Also, it seems that you manage to get around the second issue configuring IntelliJ properly.

What I can suggest is to create the project and little by little add a module then the next and so on.
This way you can understand well how it all works and get your project to use this plugin.

Best of luck with your project 👍 

Kind regards,
Gui

**Comment by AlJohri** [comment]
For anyone that ends up here from Google, I just ran into the `13:19    Error running 'MyProject': Invalid classes folder:` error repeatedly.

>Delete your conf and try "building / making" the project with its dependencies before creating a Jetty Runner configuration.

This fixed it for me. Thanks!
