### ISSUE TITLE
does it support servlet 3.0 feature web fragement and how?

### ISSUE THREAD

**Issue by xiangxingdeng** [guikeller/jetty-runner#36]

**Comment by guikeller** [comment]
Hi @xiangxingdeng,

Following below the Jetty documentation on the matter:
https://www.eclipse.org/jetty/documentation/current/configuring-webapps.html

If you bump into NoClassDefFoundError's / NoMethodFoundError's please check your classpath.

But yeah, the plugin should support that.

Cheers,
Gui
