### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by mrunaldrm** [guikeller/jetty-runner#37]
Hi,

I'm a complete newbie to intellij . I realised that it's tricky to deploy a project from intellij CE unlike how it was in eclipse.
I have a project that has few REST endpoints written using Jersey. I want to check if the response is getting generated in the correct way on local host. Can you please tell me how to do it in intellij CE using jetty.

I'm using intellij 14
JRE 8

**Comment by guikeller** [comment]
Hi @mrunaldrm ,

1) Import your project into IntelliJ and let the package manager resolve the dependencies
2) Once you have done that, build your project [ Build -> Build Project ]
3) Install the IDEA Jetty Runner plugin and restart IntelliJ
4) Run -> Edit Conf -> **+** (click on the plus sign) -> Jetty Runner -> _ReviewGenConf_ -> Ok 
5) Push play or debug (top right corner) and have fun!

Best of luck with your project! 👍 
PS: this is more a StackOverflow type of question

**Comment by mrunaldrm** [comment]
Thanks
