### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by raderio** [guikeller/jetty-runner#4]
Please make transparent icon.
![jetty-icon](https://cloud.githubusercontent.com/assets/4563564/5502335/2d3c40f4-8771-11e4-9796-fc074d93db56.png)
![jetty-server-icon](https://cloud.githubusercontent.com/assets/4563564/5502591/098f660a-8775-11e4-8abd-d38eec0cca22.png)

**Comment by guikeller** [comment]
I will look into it, thanks for the suggestion! :)

**Comment by guikeller** [comment]
Done, released on v0.0.8 - 21/01/2015
