### ISSUE TITLE
How to pass -Dspring.profiles.active=dev to Jetty Runner?

### ISSUE THREAD

**Issue by happy15** [guikeller/jetty-runner#40]
I tried to put it in VM args but it doesn't work.

**Comment by guikeller** [comment]
Hi @happy15 

I am pretty sure that the VM args are working just fine as I am using some Xms / Xmx / parameters myself for a project..

If you want to have a look at the code that takes care of that here it is:
https://github.com/guikeller/jetty-runner/blob/master/src/main/java/com/github/guikeller/jettyrunner/model/JettyRunnerCommandLine.java#L76

I suggest running your app in **debug** mode and _attaching_ the **jvisualvm** to the process and investigating which parameters are working and/or not, it may also be a typo on your conf.

If you're using spring boot you can alternatively configure the app profile on the **application.properties** file:
http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html#howto-set-active-spring-profiles

Good luck! 😄  👍

**Comment by happy15** [comment]
Thanks for the reply and It worked after I adjusted my configurations.
