### ISSUE TITLE
Gradle not able to find these jars

### ISSUE THREAD

**Issue by stevesobol** [guikeller/jetty-runner#42]
I'm trying to build jetty-runner, and Gradle can't find these jars

(logs edited for brevity)
```
20:32:46: Executing external task 'build'...
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.github.guikeller.jetty-runner:util:14.1.4.
> Could not find com.github.guikeller.jetty-runner:idea:14.1.4.
> Could not find com.github.guikeller.jetty-runner:idea_rt:14.1.4.
> Could not find com.github.guikeller.jetty-runner:openapi:14.1.4.
> Could not find com.github.guikeller.jetty-runner:annotations:14.1.4.
> Could not find com.github.guikeller.jetty-runner:jdom:14.1.4.
> Could not find com.github.guikeller.jetty-runner:extensions:14.1.4.

```
Aside from the fact that it makes no sense that you are providing your own copies of some very common Java libraries, I have been poking around the Github repo, looking at some of the closed issues and noticed that the location of the Maven repo containing these libraries has moved... but there is no reference to the new location of the repository at IndexerApp.com in build.gradle. So, gradle's looking at my hard drive, and in Maven Central, trying to find those files, and of course it's failing because the files aren't in either of those locations.

What do I need to do to fix this? I have downloaded the latest snapshot from Github. Thanks in advance.

**Comment by guikeller** [comment]
Hi @stevesobol,

Have a look at the "#create_repo.sh"
Please read the bash script and try to understand what it does.

Although it doesn't seem to make sense at first it all comes down to copyright.
As you can imagine I do not hold the rights to host the proprietary IntelliJ jars.

Also, IntelliJ does not provide a repository where I can point to.
I am sure that other plugin developers are in the same boat as me..

If you have any other questions please let me know.
Best of luck!

Cheers,
Gui

**Comment by stevesobol** [comment]
Ah, thanks for the info.

I'm using IntelliJ on Windows 10. I could take that Bash script and use it as the basis to create a PowerShell script and contribute it back to the project. Do you accept pull requests?

**Comment by guikeller** [comment]
Hi @stevesobol 

I sure do accept pull requests, other people have contributed too.
And thanks for the interest on the project, really appreciate it.

Best regards,
Gui
