### ISSUE TITLE
Each jetty start using plugin goes without last code changes

### ISSUE THREAD

**Issue by arthurdn** [guikeller/jetty-runner#43]
plugin is 1.2.0.
IDEA is 2017.2.
Could this be because of my plugin config. or IDEA cache?

**Comment by guikeller** [comment]
Hi @arthurdn,

I see that you managed to overcome the issue, would you mind sharing what was happening in a bit more detail and how did you fix it?

Thank you very much in advance.

Kind regards,
Gui

**Comment by arthurdn** [comment]
Hi! It was because of wrong IDEA cache.

BEST plugin! Thx!

**Comment by guikeller** [comment]
Hi @arthurdn 

Would you mind rating the plugin on the Jetbrains website? It would mean a lot. 
http://plugins.jetbrains.com/plugin/7505-idea-jetty-runner

Also thanks for sharing your findings, hopefully it will help others.

Cheers,
Gui

**Comment by arthurdn** [comment]
Done!
+1
