### ISSUE TITLE
how to run with spring boot

### ISSUE THREAD

**Issue by wanglingfeng** [guikeller/jetty-runner#45]
when i run with spring boot, it can't load class five. and when i don't have WebApp Folder i will get a error 'IllegalArgumentException: Number of Path(s) and Folder(s) must match: /websocket / '

**Comment by guikeller** [comment]
Here is a project structure sample and configuration:

![project_structure](https://user-images.githubusercontent.com/8213310/30896358-98b140d2-a393-11e7-90f3-ebec7832ff7b.png)

Please see the directories structure and how it is reflected on the configuration window so you can try and get it going. Unfortunately, with the information that you have provided I cannot provide any further help / advice.

Good luck
