### ISSUE TITLE
HTTP error 500 javax.servlet.ServletException: org.apache.jasper.JasperException: java.lang.IllegalStateException: No org.apache.tomcat.InstanceManager set in ServletContext

### ISSUE THREAD

**Issue by onahkenneth** [guikeller/jetty-runner#47]
I always encounter this error, please help.

### System info:
Java JDK 1.80_144-b01
JVM 64-bit (build 25.144-b01)
IntelliJ IDEA 2017.2
IDEA jettyRunner 1.2.1
Servlet 3.1.0
![screenshot from 2017-10-18 15 03 30](https://user-images.githubusercontent.com/4136156/31720292-6d6ccc3c-b416-11e7-9fd4-db31514bce05.png)

### Log:
[console.log](https://github.com/guikeller/jetty-runner/files/1394721/console.log)

**Comment by guikeller** [comment]
Hi @onahkenneth 

It seems that your JSP / Servlets have been pre-compiled for Tomcat, you have to clean the project can run it again to fix it..


```
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.jasper.JasperException: **java.lang.IllegalStateException: No org.apache.tomcat.InstanceManager set in ServletContext**
at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:176)
```

https://stackoverflow.com/questions/7725087/javax-servlet-servletexception-java-lang-noclassdeffounderror-org-apache-tomca

Nothing to do with the plugin / jetty / whatsoever.
Best of luck..

Cheers,
Gui

**Comment by onahkenneth** [comment]
I have never pre-compiled the application for tomcat. And I also cleaned the project as you suggested but still the same issue.

But when I run this project with gradle jetty plugin from the command line everything works fine.

**Comment by guikeller** [comment]
It should be a classpath issue then. 
A jsp / servlet JAR is overriding the plugin's one.

You can check out a demo project here:
https://github.com/guikeller/jetty-runner/wiki/Getting-Started

Best of luck,
Gui

**Comment by oosterholt** [comment]
I've had the same issue. We had servlet api jars in the project (javax.servlet-api-3.0.1.jar) which were included in the classpath by IntelliJ when starting Jetty. Marking the directory (only needed compile time) as excluded solved the issue for me.

**Comment by guikeller** [comment]
See issue #63 for the solution

**Comment by temmyg** [comment]
Yes, this solved my problem. Thank you Guikeller.
