### ISSUE TITLE
Moving parts to deploy on X

### ISSUE THREAD

**Issue by albfan** [guikeller/jetty-runner#49]
¿What would be the changing parts involved in deploy to X?: Tomcat, jboss, glassfish

I'm looking for guidance to provide PR or a fork to X

**Comment by guikeller** [comment]
Interesting, but then it would not be just a "Jetty-Runner" anymore, right? 😉 

Anyway, the Tomcat Runner Plugin (based on the Jetty Runner plugin) takes in the folder where the Tomcat is, you may be interested in doing something similar where the user can specify where Tomcat / JBoss / Glassfish is and deal with each one of them..

https://plugins.jetbrains.com/plugin/8266-tomcat-runner-plugin-for-intellij
https://github.com/vitorzachi/tomcat-runner

Good luck on your endeavour

**Comment by albfan** [comment]
Thanks for the link
