### ISSUE TITLE
IDEA Jetty Runner jvm version conflict

### ISSUE THREAD

**Issue by efsn** [guikeller/jetty-runner#50]
IDEA Jetty Runner plugin version is 1.2.1.
When run the webapp application, both `jdk1.7.0_75` and `jdk1.8.0_20` all throw the some error. Below is the log. What version of JVM should I use?
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/runner/Runner : Unsupported major.minor version 52.0
```

**Comment by guikeller** [comment]
Hi @efsn 

This is happening because you are not using Java 8.
> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/runner/Runner : Unsupported major.minor version 52.0
https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0/22496754

What version of JVM should I use?
> Minimum requirement: JVM / JDK / JRE v8 
https://github.com/guikeller/jetty-runner

Good luck! Cheers 😄
