### ISSUE TITLE
JVM properties field too small

### ISSUE THREAD

**Issue by fanf** [guikeller/jetty-runner#51]
I have lot of properties to configure my webapp, something like that:

```-noverify -agentpath:/.../jrebel/lib/libjrebel64.so
-javaagent:/xxx/javaagents/sizeof/SizeOf.jar
-javaagent:/xxx/javaagents/file-leak-detector/fld-1.8.jar
-DrjrDisableannotation=true 
-Drebel.lift_plugin=true
-Drebel.spring_plugin=false
-Drun.mode=production
-XX:MaxPermSize=360m
-Xms1g
-Xmx1g
-XX:-UseLoopPredicate
-XX:+UseG1GC
-XX:+UnlockExperimentalVMOptions
-XX:+UseStringDeduplication
-Drudder.configFile=/.../rudder-project/static-config/configuration-rudder-4.3.properties
-Drudder.plugin.advancedReporting.configFile=/..../rudder-project/static-config/advancedReporting-2.1.properties
-Drudder.authFile=/.../rudder-project/static-config/rudder-users.xml
-Dlogback.configurationFile=/.../workspaces/rudder-project/static-config/logback.xml`
```

It is not easy at all to modify them in the one line input text available to configure them.

**Comment by guikeller** [comment]
Hello @fanf

This should be an easy one; a TextArea with three or four lines should so the trick.

PR's are welcome!
Thanks for the feedback.

I
PS: I am on holidays at the moment.

**Comment by fanf** [comment]
Ideally, the textarea size could be adjust, because I really have a lot of parameters and prefer to pu them one per line (so I'm commonly ending up with more than 20 lines). 
But that does not make sense to force a textarea of 30 lines on everybody, because I understand that I'm kind of a special case. 

Intellij already seems to have kind of field input field for that need: an input field that can be "open" and become a bigger windows. You can see it for ex. in the Settings (ctrl+alt+s) -> Build, exec, deploy -> Compiler -> Java Compiler: the field named "additional command line parameters".
I don't know if it is hard to reuse.

**Comment by fanf** [comment]
I believe it's that: https://jetbrains.github.io/ui/controls/input_field/#input-field-types

**Comment by guikeller** [comment]
Hi @fanf 

Your wish has come through today, the VM Args field is now expandable.
Version 1.3.1 of the plugin is live, thanks for your input! Cheers

**Comment by fanf** [comment]
Oh wow fantastic! 
Sorry to not have been able to contribute it, and thanks a lot for the wonderful start of the year :)
