### ISSUE TITLE
Be able to unselect modules for webapp classpath

### ISSUE THREAD

**Issue by fanf** [guikeller/jetty-runner#52]
My project is a multi-module project, with some of them being plugins of the main webapp. The webapp loads plugins based on the availability on the classpath. 

It would be very nice to be able to unset some of the project modules from jetty runner webapp classpath so that I can make configuration with or without my webapp plugins. 

For now, I just delete or add modules in the project depending of what I need to test, but it's not very convenient.

**Comment by guikeller** [comment]
Hi @fanf,

This sure would be a nice feature.

Retrieve the list of modules:
https://github.com/guikeller/jetty-runner/blob/master/src/main/java/com/github/guikeller/jettyrunner/model/JettyRunnerCommandLine.java

Then have tick boxes to select the modules? What do you reckon?

PS: I am on holidays.

**Comment by fanf** [comment]
I don't know if you know the eclipse version of jetty runner (run-jetty-run), their version does the job: in "classpath" tab in the view here https://marketplace.eclipse.org/content/run-jetty-run#group-screenshots you can select/unselect other project (project in eclipse terminology is somehow idea intellij module, AFAIU).

Intellij seems cleaner in its notion of what a project/modules are. So if you have a way to retrieve from Intellij the list of modules and presenting them with check boxes, and then filtering out dependencies/classes of the unselect one (in JettyRunnerCommandLine.java#getClassesDirectory ?), it would be perfect from my user point of view.
