### ISSUE TITLE
Let Jetty Runner set its scope to an IntelliJ module

### ISSUE THREAD

**Issue by khituras** [guikeller/jetty-runner#57]
I have a multimodule project that looks like this

    root
    |- business-module
    |- preprocessing-module
    |- webapp-module

The important thing here is the `preprocessing-module`. It is related to the overall application but not a direct part of the `webapp-module`, that is, there are neither direct nor indirect dependencies of each other.

When I now create a new Jetty Runner configuration, it will successfully identify `webapp-module/src/main/webapp` as the webapp directory but it won't find `webapp-module/target/classes` as the classes directory (although it exists, I checked several times).
Also, when starting the web application with the Jetty Runner plugin, all dependencies of all project modules will be added to the classpath. This lead to quite some issues until I understood what was going on.

My current solution is to create an IntelliJ project of its own for the `webapp-module`. However, it would be convenient to just narrow the scope of the Jetty Runner plugin to the `webapp-module` without having the other modules intervene.

**Comment by guikeller** [comment]
Hi @khituras 

This seems to be the same request as #52 
Would you be willing to submit a PR?

Cheers!

**Comment by khituras** [comment]
#52 certainly is related. It is a more general request so I think a better solution.
I never coded an IntelliJ plugin. Also, I won’t have time in the following weeks. However, if you could provide pointers as to where to look in the existing code, I might try to implement something afterwards. Can’t promise, though.

Cheers!
Am 22. Aug. 2018, 18:12 +0200 schrieb Gui Keller <notifications@github.com>:

**Comment by guikeller** [comment]
Hi @khituras 

1) You'd need to retrieve the modules and display on the UI
On the following class you can see how to retrieve all modules L#48:
https://github.com/guikeller/jetty-runner/blob/master/src/main/java/com/github/guikeller/jettyrunner/model/JettyRunnerCommandLine.java

2) The selected modules would be added to the Model.
https://github.com/guikeller/jetty-runner/blob/master/src/main/java/com/github/guikeller/jettyrunner/model/JettyRunnerConfiguration.java

3) You would then add only the selected modules when running Jetty on "JettyRunnerCommandLine".
