### ISSUE TITLE
Get 404 Not Found Error

### ISSUE THREAD

**Issue by temmyg** [guikeller/jetty-runner#62]
Hi Gui,

I tried your instructions [here](https://github.com/guikeller/jetty-runner/wiki/Getting-Started), but when I click "Run" button in IntelliJ IDE, the new launched page always gives me "Error 404 - Not Found", regardless whatever url I have tried.

I tested in 2 different IntelliJ Community version, they are all the same. And I see that [project](https://github.com/guikeller/AngularJS-RESTful-Sample.git), instructed to use Maven Tomcat plugin to run it. I tried and it successed. So frustrating with your page.

**Comment by guikeller** [comment]
Hi @temmyg 

The 404 is a good sign, which means that the servlet container (jetty) is up and running.
On the IntelliJ console output you should see something like:

```
INFO: Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
2019-01-03 07:28:03.828:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@1a06946{/AngularJSRestful,file://path/to/workspace/AngularJS-RESTful-Sample/src/main/webapp/,AVAILABLE}{file://path/to/workspace/AngularJS-RESTful-Sample/src/main/webapp/}
2019-01-03 07:28:03.875:INFO:oejs.AbstractConnector:main: Started ServerConnector@612a51{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-01-03 07:28:03.875:INFO:oejs.Server:main: Started @2019ms
```

The important part is here:

> Started o.e.j.w.WebAppContext@1a06946{**/AngularJSRestful**,file://path/to/...

Which means that in this case the sample webapp _has been mapped_ to "**/AngularJSRestful**" so to access it browse to the following location on your preferred browser:
http://localhost:8080/AngularJSRestful

Please do let me know how you go.

Cheers,
Gui

**Comment by temmyg** [comment]
Hi @guikeller,

I got it running from your instructions, the problem I found is I missed the root path for url, it is should be /AngularJSRestful instead of the illustration on your main [page](https://github.com/guikeller/jetty-runner/wiki/Getting-Started), point 6. 

> Have fun - http://localhost:8080/AngularJS-RESTful-Sample Enjoy

thankful for your quick reply. I hope you can improve point 6 with url and screenshot, they are both different from the project settings.

**Comment by guikeller** [comment]
Hello @temmyg 

I will update the URL there, other people may bump into the same issue as you.
Also, thanks for using the plugin and giving feedback. Cheers!
