### ISSUE TITLE
Ignoring HandlerMapping

### ISSUE THREAD

**Issue by temmyg** [guikeller/jetty-runner#64]
Hi @guikeller 

I have a project [here](https://github.com/temmyg/springmvc-test1.git), now this project works fine, but when I add a "lib" directory under \webapps\WEB-INF and copy all files from lib121 to it and then click Run in IntelliJ Community, the server is launched, but it does not read request mapping information. 

Also at this time, if I just delete lib121 folder, keep only lib folder under WEB-INF, and go to "Project Structure" ---> "Modules" ---> "Dependency" tab, remove lib121's library and add "lib" as dependency library. Then click "Run" button, the server launched and the request mapping info is also not loaded. 

This seems contradictory to the Tomcat's default "lib" folder setting. Could you take a look? Thank you.

**Comment by guikeller** [comment]
Hi @temmyg ,

This has got nothing to do with the plugin.
The convention is '**WEB-INF/lib**' and not '_WEB-INF/lib121_'

Also, I recomment using **maven** to manage your dependencies and getting used to its conventions.
https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

Your question is better suited to be asked StackOverflow as this is not a bug on the plugin.
Best of luck with your studies and learning java. Cheers!

**Comment by temmyg** [comment]
@guikeller ,

If you use maven to manage the project structure, and put lib folder under the WEB-INF, you will encounter this problem. In this scenario, the plugin(or Jetty server) not reading the mapping information from Spring framework.

I think this problem for this plugin will force user to change that folder name to a different one than 'lib' in purpose for the project properly running, I tested it in IntelliJ Community edition.

**Comment by temmyg** [comment]
@guikeller 

If the user do not use maven, and accidentally put a lib folder under WEB-INF, he will encounter this issue. Not every project is maven based. There are still many are using others like Graddle etc. or not using dependency management tools.

**Comment by temmyg** [comment]
> If you use maven you won't be putting libs under "WEB-INF/lib", maven will manage the classpath for you. 😉 In addition to that, if it that was really the case can you imagine the number of complaints I would have here? The plugin would be pretty much useless. 😮
> 
> Please ask your questions on StackOverflow as is better suited for that. Best of luck. 👍

I am not asking you question, I already solved it, but it is solved not in a pleasant way because of that messing up.

**Comment by guikeller** [comment]
Good to hear, it might be that the plugin does not cater for that setup in specific.

If you require a specific setup that this plugin does not support you can either;
1) Try one of the Tomcat's plugins that are available on the marketplace
2) Support Jetbrains and purchase IntelliJ Enterprise which supports a wide range of servlet containers and application servers.

Alternatively, you could send a Pull Request with readable code, tests, and comments to this project fixing the issue that you are having. This is an OpenSource project that I maintain on my spare time giving something back to the community. I have merged Pull Requests into the main code base and released to public.

**Comment by temmyg** [comment]
That makes sense, thank you for your attentions on this side.  If I have time, I would like to contribute to this repo as well.
