### ISSUE TITLE
Problem recognising ASM Version with JDK 8

### ISSUE THREAD

**Issue by paul-french** [guikeller/jetty-runner#68]
Hi Gui

it appears that after the last IntelliJ update (to 2018.5) my jetty runner plugin stopped working. There seems to be a problem with JDK 8 and the asm version. Meanwhile I updated to IntelliJ 2019.1 but the error persosts. Would really appreciate some advice:

I am getting the following output:

> [main] INFO org.eclipse.jetty.util.log - Logging initialized @465ms to org.eclipse.jetty.util.log.Slf4jLog
> WARNING: jetty-runner is deprecated.
>          See Jetty Documentation for startup options
>          https://www.eclipse.org/jetty/documentation/
> [main] INFO org.eclipse.jetty.runner.Runner - Runner
> [main] INFO org.eclipse.jetty.server.Server - jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 1.8.0_111-b14
> [main] WARN org.eclipse.jetty.annotations.AnnotationParser - Unknown ASM version, assuming ASM7
> [main] INFO org.eclipse.jetty.annotations.AnnotationConfiguration - Scanning elapsed time=747ms
> [main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@6d8a00e3{/AEM_News,file:///D:/********/target/allure-report/,UNAVAILABLE}{file:///********/target/allure-report/}
> MultiException[java.lang.RuntimeException: Error scanning entry javax/annotation/Generated.class from jar file:///C:/Users/******/.IdeaIC2019.1/config/plugins/jetty-runner/lib/jetty-runner-9.4.14.v20181114.jar

What folows after is a list of errors scanning the jetty-runner 9.4.14.v20181114.jar. and Generated.class:

> java.lang.RuntimeException: Error scanning entry org/opentest4j/ValueWrapper.class from jar file:///C:/Users/*********/.IdeaIC2019.1/config/plugins/jetty-runner/lib/jetty-runner-9.4.14.v20181114.jar]
> 	at org.eclipse.jetty.util.MultiException.ifExceptionThrow(MultiException.java:124)
> 	at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:506)
> 	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:368)
> 	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
> 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1454)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
> 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
> 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
> 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:168)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
> 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
> 	at org.eclipse.jetty.server.Server.start(Server.java:415)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
> 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
> 	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.runner.Runner.run(Runner.java:522)
> 	at org.eclipse.jetty.runner.Runner.main(Runner.java:567)

**Comment by guikeller** [comment]
Hi @paul-french ,

That is not a plugin issue but a Jetty issue that a few others have hit.

1) https://stackoverflow.com/questions/54342609/jetty-run-meet-error-multiexceptionjava-lang-runtimeexception-error-scanning

2) https://stackoverflow.com/questions/52716062/java-lang-runtimeexception-error-scanning-entry-module-info-class-from-jar

3) https://stackoverflow.com/questions/52105680/aspectj-jetty-java-8-error-scanning-entry-updateparserfiles-class

4) https://github.com/eclipse/jetty.project/issues/1758

Google: "Jetty MultiException java.lang.RuntimeException: Error scanning entry"

I hope this helps somehow, good luck!

**Comment by guikeller** [comment]
Closing the issue as silence indicates that the issue has been solved.
