### ISSUE TITLE
Doesn't stop at breakpoints on IntelliJ 2020.1

### ISSUE THREAD

**Issue by kyungwooHyun** [guikeller/jetty-runner#71]
When I run jetty-runner as a debug mode, it doesn't stop at my breakpoints. It just runs like non-debug mode. IntelliJ version is 2020.1 and it is the same on 2020.1.1 too.

**Comment by guikeller** [comment]
Hi @kyungwooHyun 

Please look at https://github.com/guikeller/jetty-runner/issues/70
Other users have bumped into the same issue and have a workaround in place.

In addition to that I highly recommend reading the links below:
1. https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008097360-GenericDebuggerRunner-VMParametersList-params-getting-lost
2. https://github.com/guikeller/jetty-runner/issues/70#issuecomment-613954917
*Note*: The user @develar is a developer that works for IntelliJ / Jetbrains.

However, if **you** (or anyone) manage to *fix this* a **PR** is more than welcome.

**Comment by guikeller** [comment]
Fixed by https://github.com/guikeller/jetty-runner/pull/77
