### ISSUE TITLE
Dose not support servlet3 new features: @WebServlet and ServletContainerInitializer ?

### ISSUE THREAD

**Issue by BigBigWolf** [guikeller/jetty-runner#72]
jetbrains idea, worked well when use tomcat, couldn't load @WebServlet  when use jetty-runner.
Sorry my english is not good.

**Comment by guikeller** [comment]
Hi @BigBigWolf 

I have no idea how to replicate this problem.

Have a look at the Getting Started to start with:
https://github.com/guikeller/jetty-runner/wiki/Getting-Started

Get that going first, introduce the problem and commit to your own GitHub repo.
Put the link to your repo here so I can clone, reproduce and try to fix the problem.

Cheers! 👍
