### ISSUE TITLE
cannot run jetty app on intellij 

### ISSUE THREAD

**Issue by ruksad** [guikeller/jetty-runner#73]
Jetty is starting properly it gives message
2020-05-21 11:30:11,107 [main                     ] INFO  [|] org.eclipse.jetty.server.Server - Started @93401ms

but when we open page web page it says 
![jetty](https://user-images.githubusercontent.com/16033338/82555344-3592f300-9b85-11ea-8680-ff8a99eec242.PNG)

**Comment by guikeller** [comment]
Hi @ruksad 

Did you try following this? 
https://github.com/guikeller/jetty-runner/wiki/Getting-Started 

Cheers,
Gui

**Comment by ruksad** [comment]
@guikeller 
yes i have tried you example to in intellij community19.3 it does not work for me , if i hit 
http://localhost:8080/AngularJS-RESTful-Sample it gives me 404 not found

**Comment by guikeller** [comment]
Wrong URL address.

Try the following URL below
http://localhost:8080/AngularJSRestful

It is also documented on the getting started page.

```
Note: If you are getting a 404 try using this URL instead:
http://localhost:8080/AngularJSRestful
```
