### ISSUE TITLE
Allow use of different Jetty versions

### ISSUE THREAD

**Issue by shappley** [guikeller/jetty-runner#74]
By default Jetty Runner uses Jetty 9.4.x. 
For config reasons, I can only use 9.3.x.
Because of the version issue, I cannot run my applications using Jetty Runner currently. 

There is also a Jetty Runner plugin for Eclipse that gives this option, but then I have to use Eclipse...

![Screen Shot 2020-06-17 at 9 01 15 AM](https://user-images.githubusercontent.com/42483046/84901278-3ed68900-b079-11ea-9e91-85bfd784954e.png)

**Comment by guikeller** [comment]
Hi @shappley,

That sounds like a fair request, what about if I make the location of 'jetty' external?
So you/others would need to download and point to the "jetty-runner.jar" location.

By the way, the plugin version "1.2.0" could you use that version for the time being?
Let me know what you think.

Cheers!

**Comment by shappley** [comment]
>>> That sounds like a fair request, what about if I make the location of 'jetty' external? 
So you/others would need to download and point to the "jetty-runner.jar" location.

That should work.

**Comment by guikeller** [comment]
All done, I uploaded the new version of the plugin with the changes.

PS: Also read: #70

**Comment by guikeller** [comment]
Hi @shappley ,

I have uploaded the new version to Jetbrains.
Would you be able to test and provide feedback?

Cheers!

**Comment by shappley** [comment]
@guikeller 
I can take a look tomorrow. I just realized I wasn't getting an update notification for the plugin was because it's marked as compatible with version 2020.1+ only and I'm still running 2019.3. 

I'll try upgrading to IntelliJ 2020 again; hopefully JetBrains fixed some of the issues I was having with it.
