### ISSUE TITLE
Does the Intellij Idea Jetty Runner Plugin Support javax.servlet.annotation.WebServlet?

### ISSUE THREAD

**Issue by thegreatone9** [guikeller/jetty-runner#75]
Hello,

Thanks a lot for putting out the Jetty Runner plugin! I was trying to get a simple test project running with your plugin. I have noticed that when servlet mappings are done with web.xml, jetty seems to recognize the incoming requests. But with servlet annotations, the container does not seem to register the servlet mapping. 

Is it because I'm doing something wrong, or this is how it works? I am attaching pictures of my project configurations here. Thanks in advance!

![image](https://user-images.githubusercontent.com/24753782/102342233-26611000-3fc3-11eb-8a01-7b9cf7f4c37b.png)

![image](https://user-images.githubusercontent.com/24753782/102342289-3c6ed080-3fc3-11eb-83b5-30af9e122fa6.png)

![image](https://user-images.githubusercontent.com/24753782/102342435-6c1dd880-3fc3-11eb-91bb-aeec9799ace0.png)

Regards,
Musa

**Comment by guikeller** [comment]
Hi @thegreatone9 

It does, but you will need to create a servlet context listener to get hold of the servlet context.
Once you have the servlet context you can scan for the classes @WebServlet and add them to the servlet context.

_web.xml_
```xml
<web-app ...>
   <listener>
    <listener-class>
             net.therap.listeners.MyAppServletContextListener 
        </listener-class>
   </listener>
</web-app>
```

_MyAppServletContextListener.java_
```java
package net.therap.listeners;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

public class MyAppServletContextListener implements ServletContextListener{
    
    @Override
    public void contextDestroyed(ServletContextEvent servletContextEvent) {
        System.out.println("ServletContextListener destroyed");
    }

    @Override
    public void contextInitialized(ServletContextEvent servletContextEvent) {
        System.out.println("ServletContextListener started");	
        ServletContext servletContext = servletContextEvent.getServletContext();
        // This is one of the ways of doing it, see the links below as I do not know if it will work..
        servletContext.setAttribute("org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern", "**/therap/controllers/.*");
    }

}
```

The above is just an example and I have not tried or tested it.
Use it only as a general direction, you will need to dig further, test, etc.

Source(s):
https://mkyong.com/servlet/what-is-listener-servletcontextlistener-example/
https://stackoverflow.com/questions/13952661/embedded-jetty-with-annotated-servlet-patterns
https://stackoverflow.com/questions/25674206/embedded-jetty-does-not-find-annotated-servlet/41838197#41838197

Good luck with it!

Cheers,
Gui

**Comment by thegreatone9** [comment]
Thank you so much for your support! Keep up the wonderful developments!

Regards,
Musa

**Comment by guikeller** [comment]
All good, if you get a `MyAppServletContextListener` to work please share here; others might benefit greatly from it. Cheers!
