### ISSUE TITLE
Invalid Jetty Runner Path Error After Plugin Update

### ISSUE THREAD

**Issue by CodeBigBang** [guikeller/jetty-runner#76]
when I update the plugins in IDEA 2020.3, jdk1.8 to v1.4.14. 
I cannot run the jetty runner, it tell me invalid jetty runner path, 
the logs tell me to set jetty runner folder ,
is it a bug ?

**Comment by guikeller** [comment]
Hi @CodeBigBang 

As you can see from the screenshot below the conf window has changed slightly.
<p>
 <img src="https://plugins.jetbrains.com/files/7505/screenshot_22398.png">
</p>
1) Click on the link in the conf window (above) to download a jetty-runner version
2) Use the browse button to select the desired jetty-runner to run your web app

This was introduced so you have the freedom to select which jetty-runner version you want to run/use.
It also means that I do not need to update the plugin if a new version of jetty-runner is released.

Hope this helps and thanks for using the plugin!

Cheers,
Gui

**Comment by CodeBigBang** [comment]
Oh,it works, thank you for you help.
Best wishes for you.
