### ISSUE TITLE
Port setting does not take effect

### ISSUE THREAD

**Issue by dongxurr123** [guikeller/jetty-runner#8]
I set  "running on port" as 8888(or other any port)
but it always running on 8080.
OS version is win7 x64
My idea version is 14.03 community , build ver is IC-139.1117
Jetty-runner version is 0.0.9

**Comment by guikeller** [comment]
Hi Dong,

Thanks for providing the detailed info about the bug and your dev environment.
I will investigate the issue during the weekend and let you know how I go.

Cheers,
Gui

**Comment by guikeller** [comment]
Hello Dong,

I was able to reproduce the bug and fix it.
It is part of release v1.0.0 - already uploaded to JetBrains.

Please take a moment to comment and rate.
https://plugins.jetbrains.com/plugin/7505

Enjoy the plugin, cheers!
Gui

**Comment by dongxurr123** [comment]
That's great, it's an amazing plugin~
