### ISSUE TITLE
can you please make an example jetty project and commit it to demo?

### ISSUE THREAD

**Issue by firecentaur** [guikeller/jetty-runner#9]
hi there, I am having trouble getting started with jetty,

can you make a sample project and commit it into a demo folder that can be used with this runner?

**Comment by guikeller** [comment]
Hi firecentaur,

Can you please be a bit more specific? 
What are you are trying to do that you're having trouble?

I *may be able* to do something on the weekend (time allowing).

Kind regards,
Gui

**Comment by guikeller** [comment]
Hi firecentaur,

Here are some instructions on how to use the plugin in 6 easy steps.

1) Create a Java Web Application - here is a example using Maven:
http://www.mkyong.com/maven/how-to-create-a-web-application-project-with-maven/
*Note*: there are plenty of tutorials on the internet - google is your friend.

2) Import the project into IntelliJ by selecting the POM (xml) file.
Go to: File -> Import Project...

3) Install the IntelliJ Jetty Runner plugin and restart IntelliJ IDEA.
Go to: File -> Settings -> Plugins -> Browse Repositories

4) Create a Run Configuration.
Go to: Run -> Edit Configurations -> Click on the "Plus Sign" and select "Jetty Runner"
Give it a name or leave it "Unnamed" and click "Ok".

5) Run / Debug your project
Go to: Run -> Run (Shift + F10) or Run -> Debug (Shift + F9)

6) Access your web app on your localhost
On your favourite browser: http://localhost:8080/**YOUR_PROJECT_NAME**

Hope it helps and good luck! :)

Kind regards,
Gui
